apiVersion: v1
kind: Secret
metadata:
 name: dockerhub-creds
data:
 config.json: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyRnpZV05vWkdVNlUzTkFNRGd5TURJeFUzTlRjMU56IgoJCX0KCX0KfQ==
