---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: vote-ci-
spec:
  pipelineRef:
    name: instavote-ci
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: dockerhub-creds
  params:
  - name: repoUrl
    value: https://github.com/sasachde/instavote.git
  - name: revision
    value: main
  - name: sparseCheckoutDirectories
    value: /vote/
  - name: imageUrl
    value: sasachde/vote
  - name: pathToContext
    value: vote

